export {
    matras,
    stripMatras,
    stripDiacritics,
    normalizeGurbani,
    hindiToGurmukhi,
    gurmukhiToEnglish,
    toGurmukhi,
    englishToGurmukhi,
    isSimranTrigger,
    getAcronym,
    getLatinAcronym,
    getQueryAcronym,
    englishAcronymToGurmukhiRegex,
    latinAcronymMatchesLarivaar,
    cleanTranscript,
    isProbableNoise,
    isLikelyShabadHeadingLine,
    attemptLocalMatch,
    sanitizeGurmukhiText,
} from "@/shared/utils/gurbani-text-normalizer";

